// templates/frontends/vue-vite-ts/src/views/Register.vue
<template>
  <div class="flex min-h-[calc(100vh-4rem)] items-center justify-center px-4 py-12">
    <div class="w-full max-w-md space-y-8">
      <div class="text-center">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
          {{ t("register.title") }}
        </h1>
      </div>

      <form @submit.prevent="onSubmit" class="space-y-5">
        <v-text-field
          v-model="form.username"
          label="Username"
          :placeholder="t('register.usernamePlaceholder')"
          :error-messages="errors.username"
          variant="outlined"
          density="comfortable"
          hide-details="auto"
        />
        <div class="grid grid-cols-2 gap-4">
          <v-text-field
            v-model="form.first_name"
            :label="t('register.firstName')"
            :error-messages="errors.first_name"
            variant="outlined"
            density="comfortable"
            hide-details="auto"
          />
          <v-text-field
            v-model="form.last_name"
            :label="t('register.lastName')"
            :error-messages="errors.last_name"
            variant="outlined"
            density="comfortable"
            hide-details="auto"
          />
        </div>
        <v-text-field
          v-model="form.email"
          type="email"
          label="Email"
          :error-messages="errors.email"
          variant="outlined"
          density="comfortable"
          hide-details="auto"
        />
        <v-text-field
          v-model="form.password"
          type="password"
          :label="t('register.password')"
          :error-messages="errors.password"
          variant="outlined"
          density="comfortable"
          hide-details="auto"
        />
        <v-text-field
          v-model="form.confirmPassword"
          type="password"
          :label="t('register.confirmPassword')"
          :error-messages="errors.confirmPassword"
          variant="outlined"
          density="comfortable"
          hide-details="auto"
        />
        <v-btn type="submit" color="primary" block :loading="submitting" size="large">
          {{ submitting ? t("register.submitting") : t("register.submit") }}
        </v-btn>
      </form>

      <p class="text-center text-sm text-gray-600">
        {{ t("register.hasAccount") }}
        <router-link to="/login" class="font-medium text-indigo-600 hover:text-indigo-500">
          {{ t("register.loginLink") }}
        </router-link>
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { api, getErrorMessage } from "@/lib/api";
import type { RegisterFormData, RegisterResponse } from "@/types/auth";

const { t } = useI18n();
const router = useRouter();
const submitting = ref(false);

const form = reactive<RegisterFormData>({
  username: "",
  first_name: "",
  last_name: "",
  email: "",
  password: "",
  confirmPassword: "",
  country: "",
});

const errors = reactive<Record<string, string>>({});

const countryItems = COUNTRIES.filter((c) => c.code);

function validate(): boolean {
  Object.keys(errors).forEach((k) => delete errors[k as keyof typeof errors]);
  if (!form.username) errors.username = t("register.validation.usernameRequired");
  else if (form.username.length < 3) errors.username = t("register.validation.usernameMin");
  if (!form.first_name) errors.first_name = t("register.validation.firstNameRequired");
  if (!form.last_name) errors.last_name = t("register.validation.lastNameRequired");
  if (!form.email) errors.email = t("register.validation.emailRequired");
  if (!form.password) errors.password = t("register.validation.passwordRequired");
  else if (form.password.length < 8) errors.password = t("register.validation.passwordMinLength");
  if (!form.confirmPassword) errors.confirmPassword = t("register.validation.confirmPasswordRequired");
  else if (form.password !== form.confirmPassword) errors.confirmPassword = t("register.validation.passwordsNotMatch");
  return Object.keys(errors).length === 0;
}

async function onSubmit() {
  if (!validate()) return;
  submitting.value = true;
  try {
    const { data } = await api.post<RegisterResponse>("/auth/register", {
      username: form.username,
      first_name: form.first_name,
      last_name: form.last_name,
      email: form.email,
      password: form.password,
    });
    router.push("/login");
  } catch (error) {
    errors.email = getErrorMessage(error) || t("register.failed");
  } finally {
    submitting.value = false;
  }
}
</script>

// templates/frontends/react-vite-ts/src/pages/Register.tsx
import { useState } from "react";
import { useForm } from "react-hook-form";
import { useNavigate, Link } from "react-router";
import { useTranslation } from "react-i18next";
import toast from "react-hot-toast";
import { api, getErrorMessage } from "@/lib/api";
import { ROUTES } from "@/lib/routes";
import type { RegisterFormData, RegisterResponse } from "@/types/auth";

export default function Register() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [submitting, setSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<RegisterFormData>({
    defaultValues: {
      username: "",
      first_name: "",
      last_name: "",
      email: "",
      password: "",
      confirmPassword: "",
    },
  });

  const password = watch("password");

  const onSubmit = async (data: RegisterFormData) => {
    setSubmitting(true);
    try {
      const { data: res } = await api.post<RegisterResponse>("/auth/register", {
        username: data.username,
        first_name: data.first_name,
        last_name: data.last_name,
        email: data.email,
        password: data.password,
      });
      toast.success(res.message || t("register.success"));
      navigate(ROUTES.LOGIN);
    } catch (error) {
      toast.error(getErrorMessage(error) || t("register.failed"));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex min-h-[calc(100vh-4rem)] items-center justify-center px-4 py-12">
      <div className="w-full max-w-md space-y-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
            {t("register.title")}
          </h1>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
          <div>
            <label htmlFor="username" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("register.username")}
            </label>
            <input
              id="username"
              type="text"
              autoComplete="username"
              {...register("username", {
                required: t("register.validation.usernameRequired"),
                minLength: { value: 3, message: t("register.validation.usernameMin") },
              })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-indigo-400"
            />
            {errors.username && (
              <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.username.message}</p>
            )}
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label htmlFor="first_name" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                {t("register.firstName")}
              </label>
              <input
                id="first_name"
                type="text"
                autoComplete="given-name"
                {...register("first_name", {
                  required: t("register.validation.firstNameRequired"),
                })}
                className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-indigo-400"
              />
              {errors.first_name && (
                <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.first_name.message}</p>
              )}
            </div>
            <div>
              <label htmlFor="last_name" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                {t("register.lastName")}
              </label>
              <input
                id="last_name"
                type="text"
                autoComplete="family-name"
                {...register("last_name", {
                  required: t("register.validation.lastNameRequired"),
                })}
                className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-indigo-400"
              />
              {errors.last_name && (
                <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.last_name.message}</p>
              )}
            </div>
          </div>

          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("register.email")}
            </label>
            <input
              id="email"
              type="email"
              autoComplete="email"
              {...register("email", {
                required: t("register.validation.emailRequired"),
                pattern: {
                  value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                  message: t("register.validation.emailInvalid"),
                },
              })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-indigo-400"
            />
            {errors.email && (
              <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.email.message}</p>
            )}
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("register.password")}
            </label>
            <input
              id="password"
              type="password"
              autoComplete="new-password"
              {...register("password", {
                required: t("register.validation.passwordRequired"),
                minLength: { value: 8, message: t("register.validation.passwordMin") },
              })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-indigo-400"
            />
            {errors.password && (
              <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.password.message}</p>
            )}
          </div>

          <div>
            <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("register.confirmPassword")}
            </label>
            <input
              id="confirmPassword"
              type="password"
              autoComplete="new-password"
              {...register("confirmPassword", {
                required: t("register.validation.confirmPasswordRequired"),
                validate: (value) =>
                  value === password || t("register.validation.passwordsMismatch"),
              })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-indigo-400"
            />
            {errors.confirmPassword && (
              <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.confirmPassword.message}</p>
            )}
          </div>

          <button
            type="submit"
            disabled={submitting}
            className="flex w-full justify-center rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 dark:focus:ring-offset-gray-900"
          >
            {submitting ? t("register.submitting") : t("register.submit")}
          </button>
        </form>

        <p className="text-center text-sm text-gray-600 dark:text-gray-400">
          {t("register.hasAccount")}{" "}
          <Link
            to={ROUTES.LOGIN}
            className="font-medium text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
          >
            {t("register.loginLink")}
          </Link>
        </p>
      </div>
    </div>
  );
}
