// frontend/react-web/src/pages/Profile.tsx
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";
import { getErrorMessage } from "@/lib/api";
import { getProfile, updateProfile, mapProfileToFormData } from "@/services/userService";
import { COUNTRIES } from "@/constants/countries";
import { SUPPORTED_LOCALES, LOCALE_DISPLAY_CONFIG } from "@/i18n/config";
import LoadingSpinner from "@/components/ui/LoadingSpinner";
import type { ProfileUpdatePayload } from "@/types/auth";

type FormValues = ProfileUpdatePayload & { two_fa_enabled: boolean };

export default function Profile() {
  const { t } = useTranslation();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const {
    register,
    handleSubmit,
    reset,
    watch,
    setValue,
    formState: { errors, isDirty },
  } = useForm<FormValues>();

  const twoFaEnabled = watch("two_fa_enabled");

  useEffect(() => {
    (async () => {
      try {
        const profile = await getProfile();
        reset(mapProfileToFormData(profile));
      } catch (err) {
        toast.error(getErrorMessage(err));
      } finally {
        setLoading(false);
      }
    })();
  }, [reset]);

  const onSubmit = async (values: FormValues) => {
    setSaving(true);
    try {
      const payload: ProfileUpdatePayload = {
        username: values.username,
        first_name: values.first_name,
        last_name: values.last_name,
        language: values.language,
        country: values.country,
        address: values.address,
        phone: values.phone,
        two_fa_enabled: values.two_fa_enabled,
      };
      const updated = await updateProfile(payload);
      reset(mapProfileToFormData(updated));
      toast.success(t("profile.saved"));
    } catch (err) {
      toast.error(getErrorMessage(err));
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <LoadingSpinner />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-2xl px-4 py-10">
      <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
        {t("profile.title")}
      </h1>

      <form onSubmit={handleSubmit(onSubmit)} className="mt-8 space-y-6">
        <div className="grid gap-6 sm:grid-cols-2">
          <div>
            <label htmlFor="username" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("profile.username")}
            </label>
            <input
              id="username"
              {...register("username", { required: t("profile.required") })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm
                focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none
                dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            />
            {errors.username && (
              <p className="mt-1 text-xs text-red-600">{errors.username.message}</p>
            )}
          </div>

          <div>
            <label htmlFor="first_name" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("profile.firstName")}
            </label>
            <input
              id="first_name"
              {...register("first_name", { required: t("profile.required") })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm
                focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none
                dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            />
            {errors.first_name && (
              <p className="mt-1 text-xs text-red-600">{errors.first_name.message}</p>
            )}
          </div>

          <div>
            <label htmlFor="last_name" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("profile.lastName")}
            </label>
            <input
              id="last_name"
              {...register("last_name", { required: t("profile.required") })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm
                focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none
                dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            />
            {errors.last_name && (
              <p className="mt-1 text-xs text-red-600">{errors.last_name.message}</p>
            )}
          </div>

          <div>
            <label htmlFor="language" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("profile.language")}
            </label>
            <select
              id="language"
              {...register("language")}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm
                focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none
                dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            >
              {SUPPORTED_LOCALES.map((loc) => (
                <option key={loc} value={loc}>
                  {LOCALE_DISPLAY_CONFIG[loc].flag} {LOCALE_DISPLAY_CONFIG[loc].name}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label htmlFor="country" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("profile.country")}
            </label>
            <select
              id="country"
              {...register("country")}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm
                focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none
                dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            >
              {COUNTRIES.map((c) => (
                <option key={c.code} value={c.code}>
                  {c.name || t("profile.selectCountry")}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label htmlFor="phone" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("profile.phone")}
            </label>
            <input
              id="phone"
              type="tel"
              {...register("phone")}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm
                focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none
                dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            />
          </div>
        </div>

        <div>
          <label htmlFor="address" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
            {t("profile.address")}
          </label>
          <textarea
            id="address"
            rows={3}
            {...register("address")}
            className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm
              focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none
              dark:border-gray-600 dark:bg-gray-800 dark:text-white resize-none"
          />
        </div>

        <div className="flex items-center justify-between rounded-lg border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800">
          <div>
            <p className="text-sm font-medium text-gray-900 dark:text-white">
              {t("profile.twoFactorAuth")}
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              {t("profile.twoFactorDescription")}
            </p>
          </div>
          <button
            type="button"
            role="switch"
            aria-checked={twoFaEnabled}
            onClick={() => setValue("two_fa_enabled", !twoFaEnabled, { shouldDirty: true })}
            className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2
              border-transparent transition-colors duration-200 ease-in-out focus:outline-none
              focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2
              ${twoFaEnabled ? "bg-indigo-600" : "bg-gray-200 dark:bg-gray-600"}`}
          >
            <span
              className={`pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow
                ring-0 transition-transform duration-200 ease-in-out
                ${twoFaEnabled ? "translate-x-5" : "translate-x-0"}`}
            />
          </button>
        </div>

        <button
          type="submit"
          disabled={saving || !isDirty}
          className="flex w-full items-center justify-center rounded-lg bg-indigo-600 px-4 py-3
            text-sm font-semibold text-white shadow-sm hover:bg-indigo-500
            disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {saving ? <LoadingSpinner className="h-5 w-5 border-white" /> : t("profile.save")}
        </button>
      </form>
    </div>
  );
}

// templates/frontends/vue-vite-ts/src/views/Profile.vue
<template>
  <div class="mx-auto max-w-2xl px-4 py-10">
    <div v-if="loading" class="flex min-h-[60vh] items-center justify-center">
      <v-progress-circular indeterminate color="primary" size="48" />
    </div>

    <template v-else>
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">
        {{ t("profile.title") }}
      </h1>

      <form @submit.prevent="onSubmit" class="mt-8 space-y-6">
        <div class="grid gap-6 sm:grid-cols-2">
          <v-text-field
            v-model="form.username"
            :label="t('profile.username')"
            :error-messages="errors.username"
            variant="outlined"
            density="comfortable"
            hide-details="auto"
          />
          <v-text-field
            v-model="form.first_name"
            :label="t('profile.firstName')"
            :error-messages="errors.first_name"
            variant="outlined"
            density="comfortable"
            hide-details="auto"
          />
          <v-text-field
            v-model="form.last_name"
            :label="t('profile.lastName')"
            :error-messages="errors.last_name"
            variant="outlined"
            density="comfortable"
            hide-details="auto"
          />
          <v-select
            v-model="form.language"
            :label="t('profile.language')"
            :items="localeItems"
            item-title="name"
            item-value="code"
            variant="outlined"
            density="comfortable"
            hide-details
          />
          <v-select
            v-model="form.country"
            :label="t('profile.country')"
            :items="countryItems"
            item-title="name"
            item-value="code"
            variant="outlined"
            density="comfortable"
            hide-details
            clearable
          />
          <v-text-field
            v-model="form.phone"
            :label="t('profile.phone')"
            variant="outlined"
            density="comfortable"
            hide-details
          />
        </div>

        <v-textarea
          v-model="form.address"
          :label="t('profile.address')"
          variant="outlined"
          density="comfortable"
          rows="3"
          hide-details
        />

        <div class="flex items-center justify-between rounded-lg border border-gray-200 bg-gray-50 p-4">
          <div>
            <p class="text-sm font-medium text-gray-900">
              {{ t("profile.twoFactorAuth") }}
            </p>
            <p class="text-xs text-gray-500">
              {{ t("profile.twoFactorDescription") }}
            </p>
          </div>
          <v-switch v-model="form.two_fa_enabled" color="primary" hide-details />
        </div>

        <v-btn
          type="submit"
          color="primary"
          block
          size="large"
          :disabled="saving || !isDirty"
          :loading="saving"
        >
          {{ t("profile.save") }}
        </v-btn>
      </form>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import { useI18n } from "vue-i18n";
import { getProfile, updateProfile, mapProfileToFormData } from "@/services/userService";
import { getErrorMessage } from "@/lib/api";
import { COUNTRIES } from "@/constants/countries";
import { SUPPORTED_LOCALES, LOCALE_DISPLAY_CONFIG } from "@/i18n";
import type { ProfileUpdatePayload } from "@/types/auth";

const { t } = useI18n();
const loading = ref(true);
const saving = ref(false);

const form = reactive<ProfileUpdatePayload & { two_fa_enabled: boolean }>({
  username: "",
  first_name: "",
  last_name: "",
  language: "en",
  country: "",
  address: "",
  phone: "",
  two_fa_enabled: false,
});

const initialForm = ref<ProfileUpdatePayload & { two_fa_enabled: boolean } | null>(null);
const errors = reactive<Record<string, string>>({});

const isDirty = computed(() => {
  if (!initialForm.value) return false;
  return (
    form.username !== initialForm.value.username ||
    form.first_name !== initialForm.value.first_name ||
    form.last_name !== initialForm.value.last_name ||
    form.language !== initialForm.value.language ||
    form.country !== initialForm.value.country ||
    form.address !== initialForm.value.address ||
    form.phone !== initialForm.value.phone ||
    form.two_fa_enabled !== initialForm.value.two_fa_enabled
  );
});

const localeItems = SUPPORTED_LOCALES.map((loc) => ({
  code: loc,
  name: `${LOCALE_DISPLAY_CONFIG[loc].flag} ${LOCALE_DISPLAY_CONFIG[loc].name}`,
}));

const countryItems = COUNTRIES.filter((c) => c.code);

async function loadProfile() {
  try {
    const profile = await getProfile();
    const mapped = mapProfileToFormData(profile);
    Object.assign(form, mapped);
    initialForm.value = { ...mapped };
  } catch {
    // show error
  } finally {
    loading.value = false;
  }
}

function validate(): boolean {
  Object.keys(errors).forEach((k) => delete errors[k as keyof typeof errors]);
  if (!form.username) errors.username = t("profile.required");
  if (!form.first_name) errors.first_name = t("profile.required");
  if (!form.last_name) errors.last_name = t("profile.required");
  return Object.keys(errors).length === 0;
}

async function onSubmit() {
  if (!validate()) return;
  saving.value = true;
  try {
    const updated = await updateProfile({
      username: form.username,
      first_name: form.first_name,
      last_name: form.last_name,
      language: form.language,
      country: form.country,
      address: form.address,
      phone: form.phone,
      two_fa_enabled: form.two_fa_enabled,
    });
    initialForm.value = mapProfileToFormData(updated) as ProfileUpdatePayload & { two_fa_enabled: boolean };
    Object.assign(form, initialForm.value);
  } catch {
    // show error
  } finally {
    saving.value = false;
  }
}

loadProfile();
</script>
