// templates/frontends/vue-vite-ts/src/views/ResetPassword.vue
<template>
  <div class="flex min-h-[calc(100vh-4rem)] items-center justify-center px-4 py-12">
    <template v-if="!token">
      <div class="w-full max-w-md space-y-6 text-center">
        <div class="rounded-lg border border-red-200 bg-red-50 p-6">
          <p class="text-sm text-red-700">
            {{ t("resetPassword.invalidToken") }}
          </p>
        </div>
        <router-link to="/forgot-password" class="inline-block text-sm font-medium text-indigo-600 hover:text-indigo-500">
          {{ t("resetPassword.requestNewLink") }}
        </router-link>
      </div>
    </template>

    <div v-else class="w-full max-w-md space-y-8">
      <div class="text-center">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
          {{ t("resetPassword.title") }}
        </h1>
        <p class="mt-2 text-sm text-gray-600">
          {{ t("resetPassword.description") }}
        </p>
      </div>

      <form @submit.prevent="onSubmit" class="space-y-6">
        <v-text-field
          v-model="form.new_password"
          type="password"
          :label="t('resetPassword.newPassword')"
          :error-messages="errors.new_password"
          variant="outlined"
          density="comfortable"
          hide-details="auto"
        />
        <v-text-field
          v-model="form.confirmPassword"
          type="password"
          :label="t('resetPassword.confirmPassword')"
          :error-messages="errors.confirmPassword"
          variant="outlined"
          density="comfortable"
          hide-details="auto"
        />
        <v-btn type="submit" color="primary" block :loading="submitting" size="large">
          {{ submitting ? t("resetPassword.submitting") : t("resetPassword.submit") }}
        </v-btn>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { api, getErrorMessage } from "@/lib/api";

const { t } = useI18n();
const route = useRoute();
const router = useRouter();
const token = computed(() => (route.query.token as string) ?? "");
const submitting = ref(false);

const form = reactive({ new_password: "", confirmPassword: "" });
const errors = reactive<Record<string, string>>({});

function validate(): boolean {
  errors.new_password = "";
  errors.confirmPassword = "";
  if (!form.new_password) errors.new_password = t("resetPassword.validation.passwordRequired");
  else if (form.new_password.length < 8) errors.new_password = t("resetPassword.validation.passwordMinLength");
  if (!form.confirmPassword) errors.confirmPassword = t("resetPassword.validation.confirmPasswordRequired");
  else if (form.new_password !== form.confirmPassword) errors.confirmPassword = t("resetPassword.validation.passwordsNotMatch");
  return !errors.new_password && !errors.confirmPassword;
}

async function onSubmit() {
  if (!token.value || !validate()) return;
  submitting.value = true;
  try {
    await api.post("/auth/reset-password", { token: token.value, new_password: form.new_password });
    router.push("/login");
  } catch (error) {
    errors.new_password = getErrorMessage(error) || t("resetPassword.failed");
  } finally {
    submitting.value = false;
  }
}
</script>

// frontend/react-web/src/pages/ResetPassword.tsx
import { useState } from "react";
import { useForm } from "react-hook-form";
import { useNavigate, useSearchParams, Link } from "react-router";
import { useTranslation } from "react-i18next";
import toast from "react-hot-toast";
import { api, getErrorMessage } from "@/lib/api";
import { ROUTES } from "@/lib/routes";

interface ResetPasswordForm {
  new_password: string;
  confirmPassword: string;
}

export default function ResetPassword() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const token = searchParams.get("token");
  const [submitting, setSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<ResetPasswordForm>({
    defaultValues: { new_password: "", confirmPassword: "" },
  });

  const newPassword = watch("new_password");

  const onSubmit = async (data: ResetPasswordForm) => {
    if (!token) {
      toast.error(t("resetPassword.invalidToken"));
      return;
    }

    setSubmitting(true);
    try {
      await api.post("/auth/reset-password", {
        token,
        new_password: data.new_password,
      });
      toast.success(t("resetPassword.success"));
      navigate(ROUTES.LOGIN);
    } catch (error) {
      toast.error(getErrorMessage(error) || t("resetPassword.failed"));
    } finally {
      setSubmitting(false);
    }
  };

  if (!token) {
    return (
      <div className="flex min-h-[calc(100vh-4rem)] items-center justify-center px-4 py-12">
        <div className="w-full max-w-md space-y-6 text-center">
          <div className="rounded-lg border border-red-200 bg-red-50 p-6 dark:border-red-800 dark:bg-red-900/20">
            <p className="text-sm text-red-700 dark:text-red-300">
              {t("resetPassword.invalidToken")}
            </p>
          </div>
          <Link
            to={ROUTES.FORGOT_PASSWORD}
            className="inline-block text-sm font-medium text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
          >
            {t("resetPassword.requestNewLink")}
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="flex min-h-[calc(100vh-4rem)] items-center justify-center px-4 py-12">
      <div className="w-full max-w-md space-y-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
            {t("resetPassword.title")}
          </h1>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
            {t("resetPassword.description")}
          </p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <div>
            <label htmlFor="new_password" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("resetPassword.newPassword")}
            </label>
            <input
              id="new_password"
              type="password"
              autoComplete="new-password"
              {...register("new_password", {
                required: t("resetPassword.validation.passwordRequired"),
                minLength: { value: 8, message: t("resetPassword.validation.passwordMin") },
              })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-indigo-400"
            />
            {errors.new_password && (
              <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.new_password.message}</p>
            )}
          </div>

          <div>
            <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              {t("resetPassword.confirmPassword")}
            </label>
            <input
              id="confirmPassword"
              type="password"
              autoComplete="new-password"
              {...register("confirmPassword", {
                required: t("resetPassword.validation.confirmPasswordRequired"),
                validate: (value) =>
                  value === newPassword || t("resetPassword.validation.passwordsMismatch"),
              })}
              className="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-indigo-400"
            />
            {errors.confirmPassword && (
              <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.confirmPassword.message}</p>
            )}
          </div>

          <button
            type="submit"
            disabled={submitting}
            className="flex w-full justify-center rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 dark:focus:ring-offset-gray-900"
          >
            {submitting ? t("resetPassword.submitting") : t("resetPassword.submit")}
          </button>
        </form>
      </div>
    </div>
  );
}
