// templates/frontends/vue-vite-ts/src/components/Navigation.vue
<template>
  <nav class="bg-white shadow-sm border-b">
    <div class="container mx-auto px-4">
      <div class="flex items-center justify-between h-14">
        <router-link to="/" class="text-xl font-semibold text-gray-800">
          {{ t("nav.appName") }}
        </router-link>
        <div class="flex items-center gap-4">
          <LanguageSwitcher />
          <template v-if="auth.isAuthenticated">
            <router-link to="/dashboard" class="text-gray-600 hover:text-gray-900">
              {{ t("nav.dashboard") }}
            </router-link>
            <router-link to="/profile" class="text-gray-600 hover:text-gray-900">
              {{ t("nav.profile") }}
            </router-link>
            <router-link v-if="auth.isAdmin" to="/admin" class="text-gray-600 hover:text-gray-900">
              {{ t("dashboard.adminPanel") }}
            </router-link>
            <v-btn variant="text" size="small" @click="handleLogout">
              {{ t("nav.logout") }}
            </v-btn>
          </template>
          <template v-else>
            <router-link to="/login" class="text-gray-600 hover:text-gray-900">
              {{ t("nav.login") }}
            </router-link>
            <router-link to="/register" class="text-gray-600 hover:text-gray-900">
              {{ t("nav.register") }}
            </router-link>
          </template>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { useAuthStore } from "@/stores/auth";
import LanguageSwitcher from "./LanguageSwitcher.vue";

const { t } = useI18n();
const router = useRouter();
const auth = useAuthStore();

async function handleLogout() {
  await auth.logout();
  router.push("/login");
}
</script>

// templates/frontends/react-vite-ts/src/components/Navigation.tsx
import { Link } from "react-router";
import { useTranslation } from "react-i18next";
import toast from "react-hot-toast";
import { useAuth } from "@/contexts/AuthContext";
import LanguageSwitcher from "@/components/LanguageSwitcher";

export default function Navigation() {
  const { isAuthenticated, user, logout } = useAuth();
  const { t } = useTranslation();

  return (
    <nav className="bg-white shadow-sm border-b sticky top-0 z-40">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <Link to="/" className="text-xl font-bold text-indigo-600 hover:text-indigo-700 transition-colors">
            {t("nav.appName")}
          </Link>
          <div className="flex items-center gap-4">
            <LanguageSwitcher />
            {isAuthenticated ? (
              <>
                <span className="hidden sm:inline text-sm text-gray-700">
                  {t("nav.welcome", { name: user ? `${user.first_name || ""} ${user.last_name || ""}`.trim() : "" })}
                </span>
                <Link to="/dashboard" className="text-gray-700 hover:text-indigo-600 px-3 py-2 rounded-md text-sm font-medium transition-colors">
                  {t("nav.dashboard")}
                </Link>
                {user?.role === "admin" && (
                  <Link to="/admin" className="text-gray-700 hover:text-purple-600 px-3 py-2 rounded-md text-sm font-medium transition-colors">Admin</Link>
                )}
                <button onClick={() => { logout(); toast.success(t("common.logoutSuccess")); }} className="bg-red-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-red-700 transition-colors">
                  {t("nav.logout")}
                </button>
              </>
            ) : (
              <>
                <Link to="/login" className="text-gray-700 hover:text-indigo-600 px-3 py-2 rounded-md text-sm font-medium transition-colors">{t("nav.login")}</Link>
                <Link to="/register" className="bg-indigo-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-indigo-700 transition-colors">{t("nav.register")}</Link>
              </>
            )}
          </div>
        </div>
      </div>
    </nav>
  );
}
